"""sprint8_pipeline_redesign

Revision ID: 3ed4d2fd9aeb
Revises: f141c5557abc
Create Date: 2026-05-15 14:30:54.605925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed4d2fd9aeb'
down_revision: Union[str, Sequence[str], None] = 'f141c5557abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phase', sa.String(length=50), nullable=True))

    with op.batch_alter_table('process_collaborators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rag_indexed', sa.Boolean(), nullable=True))

    # Backfill: existing completed analyses get phase='completed' so the workspace
    # treats them as final reports (not Sprint-8 "collecting" stubs).
    op.execute("UPDATE analyses SET phase='completed' WHERE status='completed' AND phase IS NULL")
    op.execute("UPDATE process_collaborators SET rag_indexed=0 WHERE rag_indexed IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_collaborators', schema=None) as batch_op:
        batch_op.drop_column('rag_indexed')

    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_column('phase')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
