"""sprint5_collaborator_chat

Revision ID: f141c5557abc
Revises: c81c19524325
Create Date: 2026-05-11 13:46:00.417602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f141c5557abc'
down_revision: Union[str, Sequence[str], None] = 'c81c19524325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_collaborators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('contribution_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process_collaborators', schema=None) as batch_op:
        batch_op.drop_column('contribution_summary')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
